name: Verify install.sh

on: [push]

env:
  CDB_USER: admin
  CDB_PASSW: NzRhMjJiZDdm
# password hard coded since I cannot get the automatic creation to work

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Adopt directory structure and create .pastaELN.json
      run: |
        mkdir ../PastaData
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python/requirements.txt
    - name: Create PASTA configuration file .pastaELN.json in home directory
      run: |
        CDB_PASSW=$(python3 makeConfigFile.py work/desktop/desktop work/desktop/PastaData ${CDB_PASSW})
        echo 'password ${CDB_PASSW}'
    - name: Install CouchDB
      run: |
        sudo snap install couchdb
        sudo snap set couchdb admin=$CDB_PASSW
        sudo snap start couchdb
        sudo snap connect couchdb:mount-observe
        sudo snap connect couchdb:process-control
        sleep 5
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_users
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_replicator
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_global_changes
    - name: Run a short tests
      run: |
        wget -O- http://neuro.debian.net/lists/focal.de-fzj.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
        sudo apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9
        sudo apt-get update
        sudo apt-get install -y git-annex
        pip install datalad
        echo "======== check setup ========="
        echo "${CDB_USER} : ${CDB_PASSW}"
        more ~/.pastaELN.json
        cd Python
        ls
        echo "======= short test ============"
        python3 pastaELN.py test
        echo "======= extractor scan ======="
        python3 pastaELN.py extractorScan
        echo "==== verify installation: not executed since datalad cannot be installed somehow ====="
        # python3 Tests/verifyInstallation.py
