name: Verify install.sh

on: [push]

env:
  PASTA_DIR: PASTA
  CDB_USER: admin
  CDB_PASSW: NzRhMjJiZDdm
# password hard coded since I cannot get the automatic creation to work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install APT packages
      run: |
        sudo add-apt-repository -y universe
        sudo apt-get install -y python3 python3-pip pandoc npm
    - name: Install git, git-annex, datalad
      run: |
        wget -O- http://neuro.debian.net/lists/focal.de-fzj.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
        sudo apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9
        sudo apt-get update
        sudo apt-get install -y datalad
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python/requirements.txt
    - name: Install CouchDB
      run: |
        sudo snap install couchdb
        sudo snap set couchdb admin=$CDB_PASSW
        sudo snap start couchdb
        sudo snap connect couchdb:mount-observe
        sudo snap connect couchdb:process-control
        sleep 5
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_users
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_replicator
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_global_changes
        # I had to hard-code the username and password since is not being expandend by actions
    - name: Adopt directory structure
      run: |
        ls -l
        cwd
