name: Verify install.sh

on: [push]

env:
  CDB_USER: admin
  CDB_PASSW: NzRhMjJiZDdm
# password hard coded since I cannot get the automatic creation to work

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up system
      shell: bash
      run: |
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        # enable repo for devel git-annex, if needed
        #sudo sed -e 's|\(deb.*data\)|#\1|' -e 's|/debian |/debian-devel |' /etc/apt/sources.list.d/neurodebian.sources.list | sudo tee /etc/apt/sources.list.d/neurodebian-devel.sources.list
        sudo apt-get update -qq
        sudo apt-get install eatmydata
        sudo eatmydata apt-get install git-annex-standalone dosfstools
    - name: Set up environment
      run: |
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Adopt directory structure and create .pastaELN.json
      run: |
        mkdir ../PastaData
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python/requirements.txt
        pip install datalad
    - name: Create PASTA configuration file .pastaELN.json in home directory
      run: |
        CDB_PASSW=$(python3 makeConfigFile.py work/desktop/desktop work/desktop/PastaData ${CDB_PASSW})
        echo 'password ${CDB_PASSW}'
    - name: Install CouchDB
      run: |
        sudo snap install couchdb
        sudo snap set couchdb admin=$CDB_PASSW
        sudo snap start couchdb
        sudo snap connect couchdb:mount-observe
        sudo snap connect couchdb:process-control
        sleep 5
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_users
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_replicator
        curl -X PUT http://$CDB_USER:$CDB_PASSW@127.0.0.1:5984/_global_changes
    - name: Run a short tests
      run: |
        echo "======== check setup ========="
        echo "${CDB_USER} : ${CDB_PASSW}"
        more ~/.pastaELN.json
        cd Python
        ls
        echo "======= short test ============"
        python3 pastaELN.py test
        echo "======= extractor scan ======="
        python3 pastaELN.py extractorScan
        echo "==== verify installation: not executed since datalad cannot be installed somehow ====="
        python3 Tests/verifyInstallation.py
